- README.md
Hi! This PR is about the documentation that needed an update to show that you need to download the submodules to get music21j working correctly. I got it running on windows 8.1 with the following git commands, maybe it can be done in less steps.
git clone git://url...
cd music21j
git submodule init
git submodule update
git pull 
git submodule update --recursive.
Best regards.
Cristian Bañuelos
> Fix documentation, add: git submodule update --recursive.

- src/music21/chord.ts
- tests/moduleTests/chord.js
Vexflow sorts `StaveNote` keys based on pitch height at instantiation. When adding a modifier such as an accidental, Vexflow expects an index that corresponds to the sorted order, _not_ the insertion order. (See https://github.com/0xfe/vexflow/issues/104).
Sorting by `diatonicNoteNum` ensures that enharmonic notes are in the correct order, and receive the right modifiers.
> Chord: sort pitches by diatonicNoteNum as well as ps

- src/music21/roman.ts
- tests/moduleTests/roman.js
In music21p, the `romanNumeralAloneRegex` and `augmentedSixthRegex` regex objects use the `match` method, which restricts the search to the front of the string (see https://docs.python.org/3/library/re.html#search-vs-match). This PR imposes the same restriction on the analogous objects in JS.
> Impose music21p search restriction for Roman numeral strings

- src/music21/meter.ts
- src/music21/renderOptions.ts
- src/music21/vfShow.ts
- tests/moduleTests/beam.js
- tests/moduleTests/meter.js
With autobeam enabled, `Stream.makeBeams()` generates `Beams` objects for the stream, but these beams are NOT used when the stream is rendered to the DOM: Vexflow's `Beam.applyAndGetBeams()` is used instead. VexFlow's autobeam system is great, but suffers from issues as late as 2020 (https://github.com/0xfe/vexflow/commit/253698ea503a684e019903ff7da0d9a7036d3565).
When `renderOptions.useVexflowAutobeam` is disabled, we avoid Vexflow and the stream is instead rendered with its own beam information.
> Add useVexflowAutobeam to renderOptions

- src/music21/vfShow.ts
- tests/moduleTests/vfShow.ts
Follow-on work related to #75. In `vfShow`, retrieve `useVexflowAutobeam` from the top-level stream.
> Autobeam cleanup

- src/music21/stream.ts
- src/music21/vfShow.ts
- tests/moduleTests/stream.js
Also prefer `offset` over `getOffsetInHierarchy` for speed.
> Add site when setting elements via Stream.elements

- src/musicxml/xmlToM21.ts
Fixes #97 
Previously, jQuery made its "Intelligent Guess" of the data type, so you might get back a document object or a string, but the next method called is `scoreFromDOMTree()`, so we need to have a document object. In the linked issue I used the same example from the demo but called raw.githubusercontent.com, upon which jQuery gave me a string.
[jQuery docs](https://api.jquery.com/jQuery.get/)
> Specify data type when jQuery parses XML fetched from a URL

- src/stream.ts
This could be tightened up to avoid so much casting to `.notes() as music21.note.Note[]` or `NotRest[]`.
Noticed when working on #110, because I didn't have access to `.stemDirection` without specifying a better type.
> Type `.notes()` as providing a NotRest iterator

- src/meter.ts
- src/stream/makeNotation.ts
- tests/moduleTests/stream.ts
Ported from https://github.com/cuthbertLab/music21/pull/1068
(minus the musicxml parsing changes because m21j musicxml parsing does not manipulate measure padding yet)
> makeBeams() now distinguishes paddingRight from paddingLeft and doesn't leave stray "stop" beams in incomplete 6/8

- .gitignore
- Gruntfile.js
- package.json
- scripts/postinstall.bash
- src/note.ts
- tsconfig.json
Thanks for your patience @mttbernardini, I've added you as a co-author here so that you're credited as a repo contributor.
Fixes #58 (I'll open an issue for the second issue you mentioned)
We were waiting to fix the entry point issue until we verified we could still consume music21j's declared types in other projects when using this slimmer import of `import * as music21 from "music21j";`, which is FANTASTIC. To that end, I had to adjust the entry-point based on some changes in #93 (`main.js` instead of `debug.js`)
***
@mscuthbert this is intended to supersede both #60 and the `refactor_for_load` branch. Whatever existing procedure you have to copy files from `build` to `releases` at release-time should pick up the type declarations.
> Fix package entry point and publish type declarations

- src/stream.ts
My change in #117 actually degraded the return type to `any`, so I suggest reverting it.
> Revert change to return type of recurse()

- README.md
- src/stream.ts
- tests/moduleTests/stream.ts
**Before**
`systemWidthsAndBreaks()` calculates system breaks (against `maxSystemWidth`) without taking into account new, wider measures from reiterating clef and meter on a new system, which was only done _later_ in `fixSystemInformation()`.
**Now**
The width adjustments need to be performed in the same pass as calculating system widths, so I propose moving the logic into `systemWidthsAndBreaks()`.
> Account for measure width changes during system break calculation

- Gruntfile.js
We weren't running eslint on CI, which I noticed when CI passed on #126 without 90a21f0.
> Fix grunt eslint

- src/musicxml/xmlToM21.ts
- src/stream.ts
Saw this in a personal project again and decided to quickly fix.
- Guard against inserting elements into streams multiple times
- Avoid inserting clefs into streams twice in musicxml import (Fixes #99)
> Guard against inserting elements multiple times

- src/renderOptions.ts
- tests/moduleTests/stream.ts
m21j's native auto-beaming routines have matured to the point where we can make vexflow beaming opt-in (by setting this flag to default false).
> useVexflowAutobeam to false

- src/vfShow.ts
- tests/moduleTests/vfShow.ts
Before, ties in voices didn't render correctly, because the render flattened the stream instead of recursing.
Now, the situation is improved, for ties in voices, within a measure. Across barlines, though, we have no voice-bridging routines, so the situation is still imperfect.
For that future work, relates to https://github.com/cuthbertLab/music21/issues/1134. We probably need a keyword arg for recurse that is `voicesFirst` or something.
> Improve support for rendering ties in voices

- src/chord.ts
Fixes #146 
Now showing expected result from case on ticket:
> Sort pitches of chord before rendering vexflow

- src/stream.ts
On makeNotation() we were making accidentals on the source stream even when inPlace = false.
> bug: act on copy when makeNotation(inPlace=false)

- src/stream/makeNotation.ts
- tests/moduleTests/stream.ts
Make beams in streams employing voices, following the m21p approach of just processing each voice as a group of notes (and ignoring anything that might be loose, outside of voices).
> Make beams in voices

- src/note.ts
- tests/moduleTests/note.ts
- Rename property `lineShift` -> `stepShift` to match music21 python
- fix whole rest display on 1-line staves, see:
> lineShift -> stepShift and fix 1-line whole rest display

- src/vfShow.ts
- tests/moduleTests/vfShow.ts
Regression in ba7843b4d51cb0428eea5ea04b438a186b6e50f7.
Restores behavior from #56 reverted in #78. Adds test to prevent more churn.
> Fix regression in ties over system breaks

- src/stream.ts
- tests/moduleTests/stream.ts
Fixes some issues in `estimateStaffLength()`
1. don't return so early if voices are found: finish checking for renderOptions values for `displayKeySignature`, etc.
2. get key signature from the context (instead of depending on it being in specialContext)
> estimateStaffLength() fixes

- src/base.ts
- src/stream.ts
- src/vfShow.ts
- tests/moduleTests/vfShow.ts
Fixes tie display in voices across barlines. <s>But raises an error in Vex Flow I haven't debugged yet.</s> Fixed!
Update: moves `repeatAppend()` to `Stream`
> Fix tie display in voices across barlines and move repeatAppend() to Stream

- src/vfShow.ts
- tests/moduleTests/stream.ts
Failures to set note widths in `applyFormatterInformationToNotes()` caused downstream failures in `noteElementFromScaledX()`.
> Fix findNoteForClick() issue with notes after tuplets

- src/stream.ts
- src/vfShow.ts
- tests/moduleTests/vfShow.ts
Add `override_status` to makeNotation() and set it True when calling from prepareFlat().
Regression test fails on current version.
> Recalculate accidental display when redisplaying a stream

- src/stream.ts
- src/vfShow.ts
- tests/moduleTests/vfShow.ts
Previously, when the `showMeasureNumber` render option was used, the numbers used always began at 1, so there was no good solution for pickups.
Now, if a user has set `.number` appropriately on `Measure` objects, that number is used in lieu of the _actual_ 1-indexed position.
Regression test fails on master.
> Display measure numbers set on Measure objects if defined

- src/pitch.ts
- tests/moduleTests/pitch.ts
Port of https://github.com/cuthbertLab/music21/pull/1198
> Fix accidental status overriding for initial diatonic naturals

- src/stream.ts
- tests/moduleTests/stream.ts
`cloneEmpty()` (eventually needed for chordify/template) wasn't working, with a warning about constructors needing the `new` keyword.
> fix cloneEmpty()

- src/stream/iterator.ts
- tests/loadAll.ts
- tests/moduleTests/stream/iterator.ts
For consecutive notes n1, n2, n3, n4, n5, it was yielding [n1, n1, n1], [n3, n3, n3], [n5]  instead of [n1], [n2], [n3], [n4], [n5].
> Fix OffsetIterator

- src/musicxml/xmlToM21.ts
- src/stream.ts
(A personal project imports musicxml files.)
m21j's importer attempts to set `Part.partName` already, but it didn't exist.
> Add partName and partAbbreviation to `Part`

- src/stream.ts
- tests/moduleTests/stream.ts
Improve staff spacing when there are lyrics (reduce text collisions).
> Account for lyrics when calculating staff length

- src/key.ts
- tests/moduleTests/key.ts
`[]` signifies zero alteredPitches, not a lack of information.
Found (and fixed) as part of working on a personal project.
> Fix clearing of alteredPitches when setting sharps

- src/renderOptions.ts
- src/stream.ts
- src/vfShow.ts
- tests/moduleTests/vfShow.ts
Hide the left barline at the beginning of a single measure, a single part, or a single-part score.
One cleanup commit removes an unused option added in 8319c6f99ccac543d09043e2048add8da7821124 (unnecessary concern about backward-compat, I guess)
> Hide left barline at system beginnings

- src/duration.ts
- tests/moduleTests/duration.ts
Previously, setting dots to 0 when ql was 0 would set ql to 128.
> Fix setting dots to 0 when ql is 0

- src/meter.ts
- tests/moduleTests/meter.ts
Rely on `TimeSignature.beatGroups`, which already provides a reasonable default for 5/8 and 7/8 and can be configured by the user.
> Handle irregular beaming (e.g. 5/8 7/8)

- src/tinyNotation.ts
- tests/moduleTests/pitch.ts
Fixes #163 -- strips `"tinyNotation: "` (or lowercase) from TinyNotation strings, for compatibility with the Python `converter.parse` API.
> Strip "tinyNotation: " from TinyNotation strings

- src/tinyNotation.ts
- tests/loadAll.ts
- tests/moduleTests/tinyNotation.ts
Working a bit hastily this evening. #192 wasn't quite right -- fixed and added a test (and avoided an `indexOf` scan in case strings are long).
> Fix implementation of #192 and add test

- src/pitch.ts
- tests/moduleTests/stream.ts
Before, octaves in chords could receive superfluous accidentals if `cautionaryPitchClass`  was true (default).
#190 was incorrectly ported from python: I suppose I wasn't sure if m21j had `pitchClass` defined, but it does, so I should have just used that as the python implementation (cuthbertLab/music21#1323) does.
> Fix makeAccidentals regression involving cautionaryPitchClass and chords

- package-lock.json
- package.json
- src/articulations.ts
- src/chord.ts
- src/expressions.ts
- src/meter.ts
- src/note.ts
- src/stream.ts
- src/vfShow.ts
- tests/moduleTests/stream.ts
- tests/moduleTests/vfShow.ts
This PR replaces https://github.com/cuthbertLab/music21j/pull/172
It upgrades music21j to the current release of VexFlow.
> Vexflow 4.0.3

- src/vfShow.ts
Avoid drawing notes and rests with `hideObjectOnPrint` set to `true`.
> Don't draw hideObjectOnPrint notes/rests

- .idea/dictionaries/cuthbert.xml
- src/base.ts
- src/editorial.ts
- src/miditools.ts
- src/vfShow.ts
- tests/moduleTests/duration.ts
- tests/moduleTests/editorial.ts
- tests/moduleTests/stream.ts
- tests/moduleTests/tempo.ts
- tests/moduleTests/vfShow.ts
This allows reading and setting attributes on the Editorial object without typing it as any, making it similar to the Python version.
> type .editorial as a record for usage

- src/note.ts
- tests/moduleTests/note.ts
https://github.com/0xfe/vexflow/pull/1478 renamed `glyph` to `glyphProps`. The change was released in VexFlow v4.1.0.
> Update VexFlow glyph > glyphProps

- src/stream.ts
- tests/moduleTests/stream.ts
Background
`Stream.noteElementFromScaledX()` returns a note `n` from the stream whose leftmost x position (`n.x`) and rightmost x position (`n.x` + `n.width`) are within `allowablePixels` of the given x position. If no note falls within this range, we select the note whose leftmost and rightmost x positions are nearest to x.
Problem
It is possible for a note's rightmost x position to overlap with the next note's leftmost position. If `n1` ends at 123 and `n2` begins at 120, then an x value of 121 will return `n2`, but 122 will return `n1`!
Solution
The current PR fixes this issue by truncating note widths so that `n1` never ends after `n2` begins.
> Stream.noteElementFromScaledX(): handle note overlaps

- src/common.ts
- src/miditools.ts
MidiPlayer.player.resume()  returns nothing (in Midicube) so cannot catch console.error
Also remove a debugging console.log from common.ts
> Remove a console error

- src/stream.ts
- tests/moduleTests/stream.ts
`Part.estimateStaffLength()` calculates the staff length by incrementing measure lengths until reaching a measure with `startNewSystem`, at which point it exits. The problem with this approach is that different systems can have different estimated lengths, so any system that is longer than the first one will appear visually to be truncated when the Part is rendered to the DOM.
This PR instead calculates the lengths of all systems and then selects the longest length as the estimated length of the Part as a whole.
Small note for those who are curious: previously, when calculating the length of the first system we also included the length the first measure that appeared _after_ the system break (i.e. the measure with `startNewSystem`). This seemed wrong, but was in fact necessary as it …
> Calculate Part estimated staff length based on longest system

- src/meter.ts
- src/vfShow.ts
- tests/moduleTests/meter.ts
We have a very specific situation where `TimeSignature.getBeams()` can product a single 'stop' beam at the final note and no others. This happens when the penultimate note in a measure:
1. is beamable
2. is held across a beat
3. is preceded by a non-beamable note
4. is followed by a beamable note
This PR updates `getBeams()` to acccount for this case, and `Renderer.formatVoiceGroup()` to ensure that errors like this do not happen again.
---
```javascript
const s = new music21.stream.Measure();
s.autoBeam = true;
s.renderOptions.useVexflowAutobeam = false;
s.append(new music21.meter.TimeSignature('3/4'));
for (const ql of [0.5, 1.0, 0.75, 0.75]) {
const n = new music21.note.Note('C#', ql);
s.append(n);
}
s.replaceDOM();
```
> Prevent getBeams() from creating single stop beam

- .eslintrc.json
- src/clef.ts
- src/note.ts
- src/prebase.ts
- src/stream.ts
- src/stream/filters.ts
- src/types.ts
- tests/moduleTests/clef.ts
- tests/moduleTests/prebase.ts
not yet implemented for recurse()...
When getElementsByClass is passed a single Music21 class, like m21p, now the elements of the StreamIterator will be properly typed.
Note that it does not yet work on recurse() -- I want to make sure that even this change doesn't break my projects first.
.pitches is moved from NotRest to GeneralNote to match recent changes in m21p.
Mixing strings and M21Object classes in lists to getElements calls is no longer allowed.  Choose one or the other.
turn off eslint checking for dup methods.  Typescript checks this for us, and eslint does not know about overload methods.
rewrite clef.bestClef with modern looping techniques, and taking advantage of the automatic typing.  Add test, including recurse test.
> Proper typing for getElementsByClass

- src/stream.ts
- src/stream/iterator.ts
- tests/moduleTests/stream.ts
Bug
`Stream.getElementsByOffset()` was returning an iterator without the offset filter added.
Fix
With https://github.com/cuthbertLab/music21j/pull/239, `addFilter()` now returns a clone of the original iterator. This PR rewrites `Stream.getElementsByOffset()` to return the clone, not the original.
> Stream.getElementsByOffset() should return clone

- src/chord.ts
- src/main.ts
- src/note.ts
- src/renderOptions.ts
- src/vfShims.ts
- src/vfShow.ts
- testHTML/m21jSandbox.html
- tests/moduleTests/vfShow.ts
Lyrics have really not been working for a very long time since upgrading to Vexflow 3.  The whole system of TextNotes was not properly working with Formatter.
Replacing them with the suggested way of using Annotations.  But Annotations really, REALLY, REAALLY want to stick to the note's vertical position.  So there are a number of shims now (vfShims returns!) to make them work properly.
Still to-do:  trying to place hyphens halfway between notes.  But this is much better than the current process where they were placed on top of other notes!
> Lyrics as Vexflow annotations

- testHTML/m21jSandbox.html
Much better for debugging music21
> Sandbox stores last values

- README.md
- package.json
- src/main.ts
- src/note.ts
- src/stream.ts
- src/vfShims.ts
- src/vfShow.ts
- tests/moduleTests/vfShow.ts
The new TextAnnotation version of lyrics in VF4 is too buggy to use: lyrics are spaced beautifully normally, but can easily cause music to overflow the stave, which is impossible to use.
Temporarily restore the old version of lyrics from 0.14.x.  (All the new routines are still around (in note.ts and vfShims.ts) but are not being used.)
This will allow development of music21j to continue until VF5 is out and 5.1 can implement a stave overflow patch.
Keeping in all the non-lyric improvements from 0.15 and also the ability to specify a global lyric style.
> Restore v0.14 lyrics

- src/stream.ts
- src/stream/makeNotation.ts
- src/vfShow.ts
- tests/moduleTests/pitch.ts
Stem directions for unbeamed notes were not being calculated.  Was falling back on Vexflow determination, but Vexflow was totally wrong for chords.
> Fix stem directions for unbeamed notes

- src/stream/makeNotation.ts
Temporarily work around a Vexflow bug where chords with augmented seconds and stems down do not draw properly.
Before
After
> Augmented Second Chord Stems

- src/meter.ts
- tests/moduleTests/meter.ts
This PR removes a code block that was causing 5/4, 6/4, 7/4, 9/4, and 12/4 to create triple beat subdivisions:
__Previous__:
```typescript
const ts = new music21.meter.TimeSignature('6/4');
console.log(ts.computeBeatGroups());
>>> [[3, 8], [3, 8], [3, 8], [3, 8]]
```
__Current__:
```typescript
const ts = new music21.meter.TimeSignature('6/4');
console.log(ts.computeBeatGroups());
>>> [[2, 8]]
```
> Fix beatGroups in 5/4, 6/4, 7/4, 9/4, 12/4

- README.md
- src/articulations.ts
- src/expressions.ts
- src/instrument.ts
- src/note.ts
- src/parseLoader.ts
- testHTML/sfElsewhereCDN.html
Fixes #115
Give instructions on how to use music21j remotely without hosting yourself.
Also: Fix problems with articulations and expressions without Vexflow versions.  Make length expressions play back better.
> Improve loader docs and articulations

- src/meter.ts
- tests/moduleTests/meter.ts
Follows after https://github.com/cuthbertLab/music21j/pull/260: compound meters should have a compound beat grouping.
This PR also renames some variables, mostly just to help me follow the logic for compound meters: 
- numBeats -> meterNumerator
- beatValue -> meterDenominator
- Rewrote some code to not mutate meterNumerator, a function-scope variable
7/4 is an exception where I think [[2, 8]] makes sense.
> Fix beatGroups in 6/4, 9/4, 12/4 (take 2)

- package.json
- src/tinyNotation.ts
- tests/moduleTests/tinyNotation.ts
Allow whitespace besides non-breaking space (Breaking a use case inside comments/lyrics/etc.
in theory should be
`/[ \t\r\n\f\v\u2028\u2029]/g` but who uses form feeds or vertical tabs?
> Safer whitespace split for TinyNotation

- src/stream.ts
- tests/moduleTests/stream.ts
`Stream.createNewDOM()` adjusts the computed height of the div based on `this.renderOptions.scaleFactor.y`. We should do the same with the computed width (with `this.renderOptions.scaleFactor.x`). Without this adjustment, extra space appears to the right of the staff when `scaleFactor.x < 1.0`.
> SVG length scales with scaleFactor

- src/stream.ts
- src/tempo.ts
label places that are BPM vs QL per m.
Note some changes for later vexflow versions.
> add info about tempo

- package-lock.json
- package.json
- src/base.ts
- src/main.ts
- src/metadata.ts
- src/stream.ts
- tests/loadAll.ts
- tests/moduleTests/metadata.ts
This is nothing compared to what music21p can do, but at least allows a place to store information about titles and composers.
> Metadata -- create basic object
