cuthbertLab/music21j

- .github/workflows/ci.yml
- tests/moduleTests/pitch.js
> Run eslint on GitHub Actions CI workflow

- .idea/dictionaries/cuthbert.xml
- src/music21/chord.ts
- src/music21/musicxml/m21ToXml.ts
- src/music21/musicxml/xmlToM21.ts
- src/music21/renderOptions.ts
- src/music21/roman.ts
- src/music21/stream.ts
- src/music21/stream/iterator.ts
- src/music21/tinyNotation.ts
- src/music21/vfShow.ts
- src/music21/voiceLeading.ts
- testHTML/m21jSandbox.html
StreamIterator now knows what to expect in many cases.
> Cleanup some parts of stream with TypeScript

- src/music21/vfShow.ts
> Fix ties across systems

- src/music21/vfShow.ts
- tests/loadAll.js
- tests/moduleTests/vfShow.ts
Reinstating an old comment-out block that renders music21j beams, with a test.
> Render beams 

- src/music21/tinyNotation.ts
Enable a `chord` state token that supports lyrics: `chord{G f b d'}_V7`.
> Support chords in TinyNotation

- src/music21/stream.ts
iterating over .elements does not set activeSite.
> WIP: Ensure that playNext is always using this.flat as activeSite

- package-lock.json
- package.json
- src/music21/chord.ts
- src/music21/stream.ts
- tests/moduleTests/stream.js
Never return part > max part numbers
> findNoteForClick improvements

- src/stream/makeNotation.ts
- tests/moduleTests/stream.ts
Ported from https://github.com/cuthbertLab/music21/pull/1066
> Handle "unspecified" beam direction in middle of a beam group

- src/stream.ts
- tests/moduleTests/stream.ts
Keep m21j in sync with imminent m21p release
> inPlace defaults false in makeAccidentals

- package.json
- src/main.ts
- testHTML/demo-DragScore.html
Fixes #121   Saves 500kb on the bundle!
> Remove JQuery UI and the one place that uses it

- src/stream.ts
- tests/moduleTests/stream.ts
Port of https://github.com/cuthbertLab/music21/pull/1093
> Reiterate accidentals each measure in `makeAccidentals()`

- src/note.ts
Optimization requested in https://github.com/cuthbertLab/music21j/pull/149#discussion_r753916722.
> Optimization for 1-line whole rest fix (PR #149)

- .gitignore
- src/pitch.ts
- tests/moduleTests/pitch.ts
Port of https://github.com/cuthbertLab/music21/pull/1193
> Respect Accidental.displayType option 'never'

- src/pitch.ts
- tests/moduleTests/pitch.ts
- tests/moduleTests/vfShow.ts
Port of https://github.com/cuthbertLab/music21/pull/1197
> Fix accidental display after note intervenes between chromatic pitches

- src/stream.ts
Better tracking of JQuery originalEvent
> getUnscaledXYforDOM improvements

- src/renderOptions.ts
- src/vfShow.ts
TODO: move to enums the same time as m21p
> allow barline type 'none'

- src/meter.ts
- tests/moduleTests/meter.ts
Avoid creating impossible beams in incomplete measures.
Port of cuthbertLab/music21#1110
> Make beaming aware of paddingRight

- src/musicxml/xmlToM21.ts
Useful in a personal project and contributing back upstream.
Before, the triplets were shown/played as quarters.
> Import tuplets from musicxml

- src/pitch.ts
- src/stream.ts
- tests/moduleTests/stream.ts
Port of cuthbertLab/music21#1323
> Fix chord accidentals regression

- src/vfShow.ts
- tests/moduleTests/vfShow.ts
I needed multiple lyrics in a personal project, so I'm contributing it back upstream.
> Render multiple levels of lyrics

- .idea/dictionaries/cuthbert.xml
- Gruntfile.js
- tests/moduleTests/chord.ts
- tests/moduleTests/key.ts
- tests/moduleTests/meter.ts
- tests/moduleTests/prebase.ts
- tests/moduleTests/vfShow.ts
* key
* meter
* chord
Remove empty and redundant renders.
Better names of tests.
> Add visual and vexflow tests in more places

- src/stream.ts
- src/stream/makeNotation.ts
- tests/moduleTests/stream.ts
Port of https://github.com/cuthbertLab/music21/pull/1109
> Allow making beams according to meters from context

- src/musicxml/xmlToM21.ts
- src/stream.ts
I did this for a personal project in August and contributing back upstream.
> Parse piano music from musicxml into PartStaffs

- src/clef.ts
- src/stream.ts
- src/vfShow.ts
- tests/moduleTests/pitch.ts
- tests/moduleTests/stream.ts
Matching transition to flatten in music21p
> Use flatten() not flat internally

- src/common.ts
- tests/moduleTests/common.ts
> Fix opFrac for small values

- package-lock.json
- package.json
Trying to see if it fixed a particular bug in the direction of beams at and above C6 -- it does not.
> Update Vexflow to 4.2.1

- .gitignore
- src/vfShow.ts
just bringing some very old code to ES6 standards before doing real changes.
> Cleanup vfShow.ts

- src/note.ts
- src/vfShims.ts
MonkeyPatched Lyric: fixes alignment bug in vexflow https://github.com/vexflow/vexflow/issues/178 
Use more sophisticated estimate width code.
Support color independent of the note's.  fillColor renamed to color.
Support xShift -- note: music21 measures xShift backwards from Vexflow XShift/shift_x.
> More Lyric improvements: Alignment, X-Shift, etc.

- src/stream.ts
- src/vfShims.ts
Also fix right justification (=text-anchor end)
Tried some fixes for estimate stream length, but could not get it to work.
> Fix ties w/ lyrics

- src/note.ts
also remove flags on noStem notes.
> allow chords to have no stem
